#!/usr/bin/env python3

"""fps: Failed Password Stats"""

# Copyright (C) 2022 Eliah Kagan <degeneracypressure@gmail.com>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

from collections import Counter
import fileinput
import re
import sys

PATTERN = re.compile(r'Failed password for (?:invalid user )?(\w+)')


def main() -> None:
    """Search input for auth failure messages. Report username frequencies."""
    if len(sys.argv) < 2 and sys.stdin.isatty():
        print(f'{sys.argv[0]}: warning: no filenames and stdin is a terminal',
              file=sys.stderr)

    names = Counter(match.group(1)
                    for match in map(PATTERN.search, fileinput.input())
                    if match)

    for name, count in names.most_common():
        print(f'{count:6}  {name}')


if __name__ == '__main__':
    main()
